## DLQ variables
variable "dlq_name" {}
variable "dlq_visibility_timeout_seconds" {}
variable "dlq_delay_seconds" {}
variable "dlq_max_message_size" {}
variable "dlq_message_retention_seconds" {}
variable "dlq_receive_wait_time_seconds" {}
variable "kms_key_id" {}
variable "default_tags" {}