variable "function_name" {}
variable "description" {}
variable "role_arn" {}
variable "default_tags" {}
variable "handler" {}
variable "runtime" {}
variable "timeout" {}
variable "memory_size" {}
variable "retention_in_days" {}
variable "lg_name" {}
variable "sg_id" {}
variable "subnet_ids" {}
variable "mount_path" {}
variable "access_point_efs" {}
variable "environment_variables" {}
variable "kms_key_arn" {}